### PR TITLE
Misc Android updates

### PR DESCRIPTION
**Pull request by TacoTheDank**
- Add .cxx to the .gitignore
- Update Gradle wrapper to 6.3 using git bash
- Update Android Studio 3.4.2 -> 3.6.3
- Fix syncing with using Android Studio
- Add Java 8 support
- Update AndroidX appcompat dependency to stable 1.1.0 (we don't need core here, it's transitive of appcompat)

### CODE REVIEW

**Comment by TacoTheDank** [comment]
The CI failed, as I have come to expect.

```
0.01s$ openssl aes-256-cbc -K $encrypted_7333c7dd5b15_key -iv $encrypted_7333c7dd5b15_iv -in android/avocado.keystore.enc -out android/avocado.keystore -d
iv undefined

The command "openssl aes-256-cbc -K $encrypted_7333c7dd5b15_key -iv $encrypted_7333c7dd5b15_iv -in android/avocado.keystore.enc -out android/avocado.keystore -d" failed and exited with 1 during .
```

What even...

**Review by JaCzekanski — COMMENTED** [review]
Hi, thanks for the pull request.

AndroidX and Gradle update: all okay.

Code refactor: I don't see the point of refactoring the SDL specific code - everything in `org/libsdl/app` will be overwritten by any future SDL update anyway.
That's also the reason why I didn't bother with refactoring to Kotlin in SDL classes - that's additional code I need to maintain and wanna leave the framework code as close to stock as possible.
Unless I decide to write a separate backend for Android (not likely), I'd like to leave custom Android code as small as possible and write all emulator code in C++.

**Comment by JaCzekanski** [comment]
Hi, thanks for the pull request.
I don't see the point of refactoring the SDL specific code - everything in `org/libsdl/app` will be overwritten by any future SDL update anyway.
That's also the reason why I didn't bother with refactoring to Kotlin in SDL classes - that's additional code I need to maintain.

> The CI failed, as I have come to expect.
> 
> ```
> 0.01s$ openssl aes-256-cbc -K $encrypted_7333c7dd5b15_key -iv $encrypted_7333c7dd5b15_iv -in android/avocado.keystore.enc -out android/avocado.keystore -d
> iv undefined
> 
> The command "openssl aes-256-cbc -K $encrypted_7333c7dd5b15_key -iv $encrypted_7333c7dd5b15_iv -in android/avocado.keystore.enc -out android/avocado.keystore -d" failed and exited with 1 during .
> ```
> 
> What even...

Don't worry about that - I forgot to disable signing for PR CI builds - keystore is not available there.

**Comment by TacoTheDank** [comment]
I'll undo the last two commits, then.

**Comment by TacoTheDank** [comment]
Any updates?

**Comment by JaCzekanski** [comment]
Sorry, I didn't get any notification about new changes.
LGTM

**Pull request merged**
